@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="d-flex justify-content-between align-items-center mb-3"><h4>Partner Reports</h4><a href="{{ route('partners.index') }}" class="btn btn-light">Back to Partners</a></div>
    <form class="bg-white rounded shadow-sm p-3 mb-4 d-flex flex-wrap align-items-end gap-2"><div><label class="small text-muted">Period</label><select name="range" class="form-control"><option value="">All Time</option><option value="today" @selected(request('range') === 'today')>Today</option><option value="week" @selected(request('range') === 'week')>This Week</option><option value="month" @selected(request('range') === 'month')>This Month</option></select></div><div><label class="small text-muted">From</label><input type="date" name="from" value="{{ $from }}" class="form-control"></div><div><label class="small text-muted">To</label><input type="date" name="to" value="{{ $to }}" class="form-control"></div><button class="btn btn-primary">Apply</button></form>
    <div class="row"><div class="col-lg-6 mb-4"><div class="bg-white rounded shadow-sm p-3"><h5>Partner-wise Sales & Commission</h5><table class="table"><thead><tr><th>Partner</th><th>Qty</th><th>Revenue</th><th>Commission</th></tr></thead><tbody>@forelse($partnerRows as $row)<tr><td>{{ $row->partner_name }}</td><td>{{ number_format($row->quantity, 2) }}</td><td>₹ {{ number_format($row->revenue, 2) }}</td><td>₹ {{ number_format($row->commission, 2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No data.</td></tr>@endforelse</tbody></table></div></div>
    <div class="col-lg-6 mb-4"><div class="bg-white rounded shadow-sm p-3"><h5>Product-wise Partner Sales</h5><table class="table"><thead><tr><th>Product</th><th>Qty</th><th>Revenue</th><th>Commission</th></tr></thead><tbody>@forelse($productRows as $row)<tr><td>{{ $row->product_name }}</td><td>{{ number_format($row->quantity, 2) }}</td><td>₹ {{ number_format($row->revenue, 2) }}</td><td>₹ {{ number_format($row->commission, 2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No data.</td></tr>@endforelse</tbody></table></div></div>
    <div class="col-lg-6 mb-4"><div class="bg-white rounded shadow-sm p-3"><h5>Date-wise Commission</h5><table class="table"><thead><tr><th>Date</th><th>Commission</th></tr></thead><tbody>@forelse($dateRows as $row)<tr><td>{{ $row->sale_date }}</td><td>₹ {{ number_format($row->commission, 2) }}</td></tr>@empty<tr><td colspan="2" class="text-center text-muted">No data.</td></tr>@endforelse</tbody></table></div></div>
    <div class="col-lg-6 mb-4"><div class="bg-white rounded shadow-sm p-3"><h5>Paid vs Pending Commission</h5><table class="table"><thead><tr><th>Partner</th><th>Paid</th><th>Earned</th><th>Pending</th></tr></thead><tbody>@forelse($partners as $partner)<tr>@php($earned = (float) ($earnedRows[$partner->id] ?? 0)) @php($paid = (float) ($paidRows[$partner->id] ?? 0))<td>{{ $partner->partner_name }}</td><td>₹ {{ number_format($paid, 2) }}</td><td>₹ {{ number_format($earned, 2) }}</td><td>₹ {{ number_format(max(0, $earned - $paid), 2) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No partners.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
